### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-ulx#11]
[ERROR] gamemodes/terrortown/gamemode/client/cl_main.lua:346: attempt to index a nil value
  1. func - gamemodes/terrortown/gamemode/client/cl_main.lua:346
   2. unknown - lua/includes/extensions/net.lua:32

If you use the latest updates, you will get this error.

**Comment by TimGoll** [comment]
Hmm, it looks more like an incompatible addon or an earlier error. This happens if a team is not defined.

**Comment by dok441** [comment]
Okay, I'll look at it later in solitary.
