### ISSUE TITLE
Error when you don't have TTTC on your server

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-ulx#12]
With last version of ttt2-ulx you should get this error if you don't have TTTC installed on your server

[ERROR] addons/ttt2-ulx-master/lua/ulx/xgui/server/sv_terrortown.lua:75: attempt to index global 'CLASS' (a nil value)
  1. updateCVarsForTTTCULXClasses - addons/ttt2-ulx-master/lua/ulx/xgui/server/sv_terrortown.lua:75
   2. init - addons/ttt2-ulx-master/lua/ulx/xgui/server/sv_terrortown.lua:247
    3. fn - addons/ulx-v3_73/lua/ulx/modules/xgui_server.lua:300
     4. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

**To Reproduce**
Start a server without TTTC

**Prob fix**
Add a check if the server has TTTC installed (?)

Maybe someone else can try to replicate if it is only my bug, I no longer trust Gmod

**Comment by TimGoll** [comment]
Yes, I see the problem. Thanks for the report

**Comment by Histalek** [comment]
Was this fixed by 50f0ca84a6ae4f587e6596c92dc76bef604bd7c7 ?

**Comment by TimGoll** [comment]
Yes indeed, I forgot to close this
