### ISSUE TITLE
Hardforcenr doesnt work

### ISSUE THREAD

**Issue by TheSuspect2306** [TTT-2/ttt2-ulx#14]
Hardforcenr doesnt work, it doesnt forces you as the selected role but it takes the reserved slot from this role for example you would have 2 necromancers in this round and you will be hardforced as necro, instead of 2 necros will be this round, only one necro will be this round, same goes for traitor, you will have not 2 traitors, you will have 1 traitor

hoffe das ist so verständlich :D

**Comment by ZenBre4ker** [comment]
This should be fixed by https://github.com/TTT-2/TTT2/pull/685 in October 2020
