### ISSUE TITLE
Impossible to play 

### ISSUE THREAD

**Issue by MisterClems** [TTT-2/ttt2-ulx#17]
With the last  github  version of TTT2 , ULX ,ULIB and ULXTTT2 its impossible to spawn, start round ect....
![Capture](https://user-images.githubusercontent.com/73431903/138327075-89ae9ac3-cab0-4551-92a2-d3de67e553ce.PNG)

Happen only when i install ULX  TTT2

**Comment by TimGoll** [comment]
why do you think that we have different versions?

**Comment by TimGoll** [comment]
Ah there we go. I have this error as well, I just didn't notice it. I will take a look at it

**Comment by MisterClems** [comment]
> 
> 
> Interesting. The version you're using is also 3 years old. Are you using a github version?

yeah on github its the last version i have check when i directly download master branch my ulib is 2.70d but the last in list is this one on tag so idk 
![image](https://user-images.githubusercontent.com/73431903/138331170-85654708-ab10-48a5-bccf-f0091fc0eec2.png)

**Comment by MisterClems** [comment]
![1](https://user-images.githubusercontent.com/73431903/138332165-409ae80e-8fe7-4d9f-92ff-a3f9d153380f.PNG)
![2](https://user-images.githubusercontent.com/73431903/138332170-54d2b2ca-70b6-4023-b557-e62a5bac2f40.PNG)
![3](https://user-images.githubusercontent.com/73431903/138332175-80c257ca-ff19-4e26-8e40-4beea3ae899a.PNG)

**Comment by TimGoll** [comment]
where exactly did you get the version 2.7.0? The newest release on GitHub is 2.6.3
