### ISSUE TITLE
cant force a role via force / forcenr

### ISSUE THREAD

**Issue by wiliam969** [TTT-2/ttt2-ulx#3]
im getting the following error:

`[Update] lua/ulx/modules/sh/ttt_admin.lua:418: attempt to index local 'tbl' (a nil value)
1. GetLoadoutWeapons - lua/ulx/modules/sh/ttt_admin.lua:418
2. RemoveLoadoutWeapons - lua/ulx/modules/sh/ttt_admin.lua:454
3. call - lua/ulx/modules/sh/ttt_admin.lua:370
4. __fn - addons/ulib-v2_63/lua/ulib/shared/commands.lua:943
5. execute - addons/ulib-v2_63/lua/ulib/shared/commands.lua:1323
6. unknown - addons/ulib-v2_63/lua/ulib/shared/commands.lua:1351
7. Run - lua/includes/modules/concommand.lua:54
8. unknown - addons/ulib-v2_63/lua/ulib/shared/commands.lua:1365
9. unknown - lua/includes/modules/concommand.lua:54
`

im using ulib v2.63 ulx v3.73

also coud'nt determine where this error comes from :
`[ERROR] gamemodes/terrortown/entities/entities/ttt_role_counter/cl_init.lua:23: attempt to concatenate field 'string' (a nil value)
1. func - gamemodes/terrortown/entities/entities/ttt_role_counter/cl_init.lua:23
2. unknown - lua/includes/extensions/net.lua:32`

**Comment by Alf21** [comment]
I will fix this. Thanks for bug report!

**Comment by Histalek** [comment]
As this seems fixed and there are no complaints for over a year now i'm closing this issue.

Feel free to reopen if it is not fixed :)
